/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as CShareIdRouteImport } from './routes/c/$shareId'
import { Route as AppChecklistIdRouteImport } from './routes/app/$checklistId'
import { Route as AppFeaturedFeaturedIdRouteImport } from './routes/app/featured/$featuredId'
import { Route as ApiChecklistsShareRouteImport } from './routes/api/checklists/share'
import { Route as ApiChecklistsShareShareIdRouteImport } from './routes/api/checklists/share.$shareId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const CShareIdRoute = CShareIdRouteImport.update({
  id: '/c/$shareId',
  path: '/c/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChecklistIdRoute = AppChecklistIdRouteImport.update({
  id: '/app/$checklistId',
  path: '/app/$checklistId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFeaturedFeaturedIdRoute = AppFeaturedFeaturedIdRouteImport.update({
  id: '/app/featured/$featuredId',
  path: '/app/featured/$featuredId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChecklistsShareRoute = ApiChecklistsShareRouteImport.update({
  id: '/api/checklists/share',
  path: '/api/checklists/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChecklistsShareShareIdRoute =
  ApiChecklistsShareShareIdRouteImport.update({
    id: '/$shareId',
    path: '/$shareId',
    getParentRoute: () => ApiChecklistsShareRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/$checklistId': typeof AppChecklistIdRoute
  '/c/$shareId': typeof CShareIdRoute
  '/app/': typeof AppIndexRoute
  '/api/checklists/share': typeof ApiChecklistsShareRouteWithChildren
  '/app/featured/$featuredId': typeof AppFeaturedFeaturedIdRoute
  '/api/checklists/share/$shareId': typeof ApiChecklistsShareShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/$checklistId': typeof AppChecklistIdRoute
  '/c/$shareId': typeof CShareIdRoute
  '/app': typeof AppIndexRoute
  '/api/checklists/share': typeof ApiChecklistsShareRouteWithChildren
  '/app/featured/$featuredId': typeof AppFeaturedFeaturedIdRoute
  '/api/checklists/share/$shareId': typeof ApiChecklistsShareShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/$checklistId': typeof AppChecklistIdRoute
  '/c/$shareId': typeof CShareIdRoute
  '/app/': typeof AppIndexRoute
  '/api/checklists/share': typeof ApiChecklistsShareRouteWithChildren
  '/app/featured/$featuredId': typeof AppFeaturedFeaturedIdRoute
  '/api/checklists/share/$shareId': typeof ApiChecklistsShareShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/$checklistId'
    | '/c/$shareId'
    | '/app/'
    | '/api/checklists/share'
    | '/app/featured/$featuredId'
    | '/api/checklists/share/$shareId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/$checklistId'
    | '/c/$shareId'
    | '/app'
    | '/api/checklists/share'
    | '/app/featured/$featuredId'
    | '/api/checklists/share/$shareId'
  id:
    | '__root__'
    | '/'
    | '/app/$checklistId'
    | '/c/$shareId'
    | '/app/'
    | '/api/checklists/share'
    | '/app/featured/$featuredId'
    | '/api/checklists/share/$shareId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppChecklistIdRoute: typeof AppChecklistIdRoute
  CShareIdRoute: typeof CShareIdRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiChecklistsShareRoute: typeof ApiChecklistsShareRouteWithChildren
  AppFeaturedFeaturedIdRoute: typeof AppFeaturedFeaturedIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$shareId': {
      id: '/c/$shareId'
      path: '/c/$shareId'
      fullPath: '/c/$shareId'
      preLoaderRoute: typeof CShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$checklistId': {
      id: '/app/$checklistId'
      path: '/app/$checklistId'
      fullPath: '/app/$checklistId'
      preLoaderRoute: typeof AppChecklistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/featured/$featuredId': {
      id: '/app/featured/$featuredId'
      path: '/app/featured/$featuredId'
      fullPath: '/app/featured/$featuredId'
      preLoaderRoute: typeof AppFeaturedFeaturedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checklists/share': {
      id: '/api/checklists/share'
      path: '/api/checklists/share'
      fullPath: '/api/checklists/share'
      preLoaderRoute: typeof ApiChecklistsShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checklists/share/$shareId': {
      id: '/api/checklists/share/$shareId'
      path: '/$shareId'
      fullPath: '/api/checklists/share/$shareId'
      preLoaderRoute: typeof ApiChecklistsShareShareIdRouteImport
      parentRoute: typeof ApiChecklistsShareRoute
    }
  }
}

interface ApiChecklistsShareRouteChildren {
  ApiChecklistsShareShareIdRoute: typeof ApiChecklistsShareShareIdRoute
}

const ApiChecklistsShareRouteChildren: ApiChecklistsShareRouteChildren = {
  ApiChecklistsShareShareIdRoute: ApiChecklistsShareShareIdRoute,
}

const ApiChecklistsShareRouteWithChildren =
  ApiChecklistsShareRoute._addFileChildren(ApiChecklistsShareRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppChecklistIdRoute: AppChecklistIdRoute,
  CShareIdRoute: CShareIdRoute,
  AppIndexRoute: AppIndexRoute,
  ApiChecklistsShareRoute: ApiChecklistsShareRouteWithChildren,
  AppFeaturedFeaturedIdRoute: AppFeaturedFeaturedIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
